fix extracting old style hashes
since the changes to accomodate the new hash format
from the newer nix-daemon, the old style hashes have
not been parsed correctly. This fixes nix-prefetch
for handling these types of errors:

```
hash mismatch in fixed-output derivation '/nix/store/3lp6m6wyc117nmam1wmfcz366hb45ll6-source':
  wanted: sha256:0000000000000000000000000000000000000000000000000000
  got:    sha256:0032misdkvw2k1vs9dg17vzfn35m0i1839ls8y5jj6aq0pb9x1dl
error: build of '/nix/store/l7h3bbm2fdkqnja9v5rag97dg1ym4z6j-source.drv' failed
```